export const ACCESS_CODE = 'ACCESS_CODE';
export const INVALID_ACCESS_CODE = 'INVALID_ACCESS_CODE';
export const NO_ACCESS_CODE = 'NO_ACCESS_CODE';
export const GATED_ADDRESS = 'GATED_ADDRESS';
export const ADDRESS = 'ADDRESS';

export const ADDRESS_QUESTIONNAIRE = 'ADDRESS_QUESTIONNAIRE';
export const ADDRESS_NOT_ACCESSIBLE = 'ADDRESS_NOT_ACCESSIBLE';
export const PREFER_POD = 'PREFER_POD';

export const SINGLE_HOUSE = 'SINGLE_HOUSE';
export const APARTMENT_COMPLEX = 'APARTMENT_COMPLEX';
export const COMMERCIAL_BUILDING = 'COMMERCIAL_BUILDING';

export const DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;
export const QUESTIONNAIRE_PROPERTIES = ['address_type', 'address_characteristic', 'delivery_reason'];

export const DELIVERY_ADDRESS = 'DELIVERY_ADDRESS';
export const DELIVERY_INSTRUCTION = 'DELIVERY_INSTRUCTION';
export const DELIVERY_PREFER_POD = 'DELIVERY_PREFER_POD';

export const CHARACTERISTIC_HOUSE_GATED = 'HOUSE_GATED';
export const CHARACTERISTIC_GATED = 'GATED';
export const CHARACTERISTIC_HIGH_RISE = 'HIGH-RISE';
